# Generated by Django 4.0 on 2021-12-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='created_by',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_active',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_exchange',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='strike_price_gap',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='updated_by',
            field=models.IntegerField(default='0'),
        ),
    ]
