# Generated by Django 4.0 on 2021-12-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_stock_created_by_stock_is_active_stock_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_exchange',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='strike_price_gap',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
