# Generated by Django 4.0 on 2021-12-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_alter_stock_name_alter_stock_stock_exchange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='is_active',
            field=models.IntegerField(default='1'),
        ),
    ]
