# Generated by Django 4.0 on 2021-12-23 05:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_alter_stock_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 23, 5, 21, 55, 133974, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 23, 5, 21, 55, 133974, tzinfo=utc)),
        ),
    ]
