# Generated by Django 4.0 on 2021-12-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_alter_stock_created_at_alter_stock_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='created_by',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='updated_by',
            field=models.IntegerField(default='1'),
        ),
    ]
