# Generated by Django 4.0 on 2022-01-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_alter_stock_created_by_alter_stock_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='updated_at',
        ),
    ]
